# Site settings
title: h a p p y b i r t h d a y e r i c !
description: 
baseurl: /
url: https://its100percentreal.github.io/hbd.io

# User settings
username: happy birthday eric!
user_description: 
user_title: 
# email: 
# twitter_username: 
# github_username:  
# gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
